spring:
  application:
    name: MarketPulse

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:5433/marketpulse
    username: marketpulse_user
    password: marketpulse_password

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

twelve-data:
  api:
    base-url: https://api.twelvedata.com
    api-key: ${TWELVE_DATA_API_KEY}