spring:
  application:
    name: MarketPulse

  data:
    redis:
      host: localhost
      port: 6379

  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
      - org.springframework.boot.flyway.autoconfigure.FlywayAutoConfiguration

twelve-data:
  api:
    base-url: https://api.twelvedata.com
    api-key: ${TWELVE_DATA_API_KEY}